trigger:
  - main

pool:
  vmImage: 'windows-latest'

steps:
  - task: AzurePowerShell@5
    inputs:
      azureSubscription: 'AzureSPConnection'
      ScriptType: 'InlineScript'
      azurePowerShellVersion: 'LatestVersion'  
      Inline: |
        # Variables
        $vaultName = "RecoveryVault"
        $rgName = "RecoveryRG"
        $recoveryPlanName = "PrimaryVMRecoveryPlan"

        # Initiate a Test Failover
        $rp = Get-AzRecoveryServicesAsrRecoveryPlan -ResourceGroupName $rgName -Name $recoveryPlanName -VaultId (Get-AzRecoveryServicesVault -Name $vaultName).Id
        Start-AzRecoveryServicesAsrTestFailoverJob -InputObject $rp -NetworkId /subscriptions/5518087e-908d-4cb5-ac6a-d09d9eef4fb6/resourceGroups/RecoveryRG/providers/Microsoft.Network/virtualNetworks/RecoveryVNet

  - task: AzurePowerShell@5
    inputs:
      azureSubscription: 'AzureSPConnection'
      ScriptType: 'InlineScript'
      azurePowerShellVersion: 'LatestVersion'
      Inline: |
        # Variables
        $vaultName = "RecoveryVault"
        $rgName = "RecoveryRG"
        $recoveryPlanName = "PrimaryVMRecoveryPlan"

        # Cleanup Test Failover
        $rp = Get-AzRecoveryServicesAsrRecoveryPlan -ResourceGroupName $rgName -Name $recoveryPlanName -VaultId (Get-AzRecoveryServicesVault -Name $vaultName).Id
        Stop-AzRecoveryServicesAsrTestFailoverJob -InputObject $rp
        Write-Host "Cleanup Completed Successfully."
